project:
  type: book
  render: 
    - "*.qmd"
    - "!*.md"
resources:
  - CNAME
book:
  title: "NHSOA-way"
  author: "NHS-OA Community"
  date: last-modified
  comments:
    hypothesis: true
  chapters:
    - index.qmd
    - nhsoa-vision.qmd
    - part: get-involved.qmd
      chapters:
        - coffee-and-code.qmd
        - training.qmd
        - webinars.qmd
        - workshops.qmd
        - blogs.qmd
        - code_contribution.qmd
    - part: our_ways.qmd
      chapters:
        - nhsoa-committee.qmd
        - CODE_OF_CONDUCT.qmd
        - nhsoa-fellows.qmd
        - style-guides.qmd
        - accessibility.qmd

  page-footer:
    left: |
      NHS-OA Way by the NHS-OA Community
      
      NHS-OA Community makes all of their materials publicly available under open source licenses
    right: |
      This unofficial book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/nhs-oa-community/NHSOA-way/
  repo-branch: main
  repo-actions: [edit, issue]
  site-url: https://nhsoa-way.nhsoa.co.uk/

format:
  html:
    theme: cosmo
