# NHS-OA Community Committee {#committee .unnumbered}

NHS-OA Community has a Committee, details are below, and this reports to a 
Steering Group whose membership is made up of The Strategy Unit colleagues.

## Terms of Reference {#committee}

## Purpose

The purpose of the committee is to:

* agree and support the purpose for the NHS-OA Community.
* develop and deliver a programme to support the purpose which has included 
webinars, workshops, and conferences.
* make the NHS-OA Community a welcome and inclusive space where members can share, 
connect and support each other.  
* steer the direction and vision of NHS-OA Community by making use of available 
data such as survey results, engagement statistics and event attendance reports. 

## Governance

The working group is chaired by a representative from the hosting body, the 
Strategy Unit, who will have overall responsibility for the governance and 
financial running of NHS-OA Community.

As part of the support from The Strategy Unit administrative support is provided 
to manage the events held as part of NHS-OA Community and will be available to 
take brief notes. 

Meetings will be held regularly and dependent upon requirements of NHS-OA 
Community at a minimum of once a month.

## Membership

The committee will comprise volunteer representatives of the wider community 
including NHS, central government, local government, public sector, voluntary, 
charities and academia. 
Whilst no one will be prevented from joining who is not currently employed by 
any of these organisations it is expected that individuals are mindful of the 
purpose of NHS-OA Community to promote the use of open-source data science tools 
within these organisations specifically.

Members will be asked to meetings, at a minimum of monthly, and where possible 
volunteer for additional tasks to support NHS-OA Community, as well as 
disseminating information about NHS-OA Community to their own networks.
Members will be asked to reconfirm their commitment to the group every six months. 
There will be no specific limitation to the size of the Committee as it is 
recognised that this Committee may create sub-groups to support particular 
activities.

## Outputs

Lead on the development of a schedule of community meetups, encouraging wider 
collaboration beyond the NHS and the domain knowledge of open source coding 
languages.

Develop a communications and engagement strategy for the community.

Establish an evaluation process to ascertain impact/effectiveness of the 
community initiatives.

Lead on development of the community-led handbook NHS-OA Way.

Support the establishment and management of subcommunities.

## Meetings

Working group meetings to be held at least every month for one hour with minutes 
to be shared publicly on the NHS-OA Community GitHub. 

Meetings will increase in frequency as determined by the group, particularly in 
preparation for large events like conferences.

## Minutes

Once agreed minutes will be uploaded as markdown files to the [NHS-OA Community 
GitHub repository](https://github.com/nhs-oa-community/committee_meetings_open)