name: spellcheck

on:
  push:

jobs:
  spellcheck:
    name: runner / spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v7

      - name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.66.0
